# Local Variables
MEDIA_PATH: /mnt/media
CONTAINERS_PATH: /mnt/containers
# ProtonVPN
PROTONVPN_USERNAME:
PROTONVPN_PASSWORD:
PROTONVPN_SERVER:
PROTONVPN_TIER:
# Transmission
TRANSMISSION_USERNAME:
TRANSMISSION_PASSWORD:
