---
- name: Ensure container-selinux is installed
  ansible.builtin.package:
    name: container-selinux
    state: present

- name: Ensure Podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure Podman service is running
  ansible.builtin.service:
    name: podman
    state: started
    enabled: yes

- name: Pull wireguard image
  containers.podman.podman_image:
    name: ''
    tag: latest

- name: Create directories for wireguard container
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '/opt/nextcloud'

- name: Create and run wireguard container
  containers.podman.podman_container:
    name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    restart_policy: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=wireguard.lemarte.tech
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
    volumes:
      - /path/to/appdata/config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

- name: Start nextcloud container
  ansible.builtin.systemd :
    name: "container-nextcloud.service"
    enabled: true
    state: startedw