--- # https://github.com/tprasadtp/protonvpn-docker
- name: Ensure container-selinux is installed
  ansible.builtin.package:
    name: container-selinux
    state: present

- name: Ensure Podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure Podman service is running
  ansible.builtin.service:
    name: podman
    state: started
    enabled: "yes"

- name: Pull protonwire image
  containers.podman.podman_image:
    name: "ghcr.io/tprasadtp/protonwire:latest"
    tag: latest

- name: Start ProtonWire container
  containers.podman.podman_container:
    name: protonwire
    image: ghcr.io/tprasadtp/protonwire:latest
    state: started
    interactive: yes
    tty: yes
    remove: yes
    init: yes
    timezone: local
    cap_add:
      - NET_ADMIN
    sysctl:
      net.ipv4.conf.all.rp_filter: 2
    tmpfs:
      "/tmp": ""
    volumes:
      - type: bind
        source: /home/tlemarte/HomelabIAC/playbooks/roles/protonwire/files/private.key
        target: /etc/protonwire/private-key
        read_only: true
    env:
      PROTONVPN_SERVER: "SE#4"
    ports:
      - "8000:80"
      # For transmission
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
      # For prowlarr
      - "9696:9696"
      # For sonarr
      - "8989:8989"
      # For radarr
      - "7878:7878"
      # For lidarr
      - "8686:8686"
      # For bazarr
      - "6767:6767"
      # For readarr
      - "8787:8787"