---
#------ Lidarr <https://github.com/linuxserver/docker-lidarr> ------
# https://wiki.servarr.com/lidarr
- name: Run lidarr container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull lidarr image
      containers.podman.podman_image:
        name: "lscr.io/linuxserver/lidarr"
        tag: latest

    - name: Create directories for lidarr container
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ CONTAINERS_PATH }}/lidarr"
        - "{{ CONTAINERS_PATH }}/lidarr/config"
        - "{{ MEDIA_PATH }}/music"
        - "{{ MEDIA_PATH }}/downloads/complete"

    - name: Create lidarr container
      containers.podman.podman_container:
        name: lidarr
        image: "lscr.io/linuxserver/lidarr:latest"
        # Next two are managed by systemd
        state: created
        restart_policy: "no"
        privileged: true
        # Storage works after running the following, why?
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context="system_u:object_r:container_file_t:s0",nolock /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        device:
          - "{{ CONTAINERS_PATH }}/lidarr/config:/config:rwm"
          - "{{ MEDIA_PATH }}/music:/music:rwm"
          - "{{ MEDIA_PATH }}/downloads/complete:/downloads:rwm"
        volume:
          - "{{ CONTAINERS_PATH }}/lidarr/config:/config"
          - "{{ MEDIA_PATH }}/music:/music"
          - "{{ MEDIA_PATH }}/downloads/complete:/downloads"
        network: "container:protonvpn"
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/Los_Angeles
        generate_systemd:
          path: "/etc/systemd/system/"
          new: "yes"
          restart_policy: "on-failure"

    - name: Start lidarr container
      ansible.builtin.systemd :
        name: "container-lidarr.service"
        enabled: true
        state: started