---
#------ Jellyfin <https://github.com/linuxserver/docker-jellyfin> ------
- name: Run jellyfin container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull jellyfin image
      containers.podman.podman_image:
        name: "lscr.io/linuxserver/jellyfin"
        tag: latest

    - name: Create directories for jellyfin container
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ MEDIA_PATH }}/tvshows"
        - "{{ MEDIA_PATH }}/movies"
        - "{{ MEDIA_PATH }}/music"
        - "{{ MEDIA_PATH }}/audiobooks"
        - "{{ CONTAINERS_PATH }}/jellyfin/config"

    - name: Create jellyfin container
      containers.podman.podman_container:
        name: jellyfin
        image: "lscr.io/linuxserver/jellyfin:latest"
        # Next two are managed by systemd
        state: created
        restart_policy: "no"
        privileged: true
        # Storage works after running the following, why?
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context="system_u:object_r:container_file_t:s0",nolock /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        device:
          - "{{ MEDIA_PATH }}/tvshows:/data/tvshows:rwm"
          - "{{ MEDIA_PATH }}/movies:/data/movies:rwm"
          - "{{ MEDIA_PATH }}/music:/data/music:rwm"
          - "{{ MEDIA_PATH }}/audiobooks:/data/audiobooks:rwm"
          - "{{ CONTAINERS_PATH }}/jellyfin/config:/config:rwm"
        volume:
          - "{{ MEDIA_PATH }}/tvshows:/data/tvshows"
          - "{{ MEDIA_PATH }}/movies:/data/movies"
          - "{{ MEDIA_PATH }}/music:/data/music"
          - "{{ MEDIA_PATH }}/audiobooks:/data/audiobooks"
          - "{{ CONTAINERS_PATH }}/jellyfin/config:/config"        
        ports:
          - "8096:8096"
          - "8920:8920"
          - "7359:7359/udp"
          - "1900:1900/udp"
        env:
          PUID: 1000
          PGID: 1000
          TZ: "America/Los_Angeles"
        generate_systemd:
          path: "/etc/systemd/system/"
          new: "yes"
          restart_policy: "on-failure"

    - name: Start jellyfin container
      ansible.builtin.systemd :
        daemon_reload: true
        name: "container-jellyfin.service"
        enabled: true
        state: started