#------ Lidarr <https://github.com/linuxserver/docker-lidarr> ------ 
# https://wiki.servarr.com/lidarr
- name: Run lidarr container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull lidarr image
      containers.podman.podman_image:
        name: 'lscr.io/linuxserver/lidarr'
        tag: latest

    - name: Create directories for lidarr container
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '/mnt/containers/lidarr'
        - '/mnt/containers/lidarr/config'
        - '/mnt/media/music'
        - '/mnt/media/downloads/complete'

    - name: Create lidarr container
      containers.podman.podman_container:
        name: lidarr
        image: 'lscr.io/linuxserver/lidarr:latest'
        state: started
        restart_policy: unless-stopped
        privileged: true
        # Storage works after running the following, why?
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context='system_u:object_r:container_file_t:s0' /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        device:
          - '/mnt/containers/lidarr/config:/config:rwm'
          - '/mnt/media/music:/music:rwm'
          - '/mnt/media/downloads/complete:/downloads:rwm'
        network: 'container:protonvpn'
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/Los_Angeles
