#------ Nextcloud <https://github.com/linuxserver/docker-nextcloud> ------ 
- name: Run nextcloud container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull nextcloud image
      containers.podman.podman_image:
        name: 'lscr.io/linuxserver/nextcloud'
        tag: latest

    - name: Create directories for nextcloud container
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '/mnt/containers/nextcloud'
        - '/mnt/containers/nextcloud/config'
        - '/mnt/containers/nextcloud/data'

    - name: Create nextcloud container
      containers.podman.podman_container:
        name: nextcloud
        image: 'lscr.io/linuxserver/nextcloud:latest'
        state: started
        restart_policy: unless-stopped
        privileged: true
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context="system_u:object_r:container_file_t:s0",nolock /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        # Why do I need to do both device and volume?
        device:
          - '/mnt/containers/nextcloud/config:/config:rwm'
          - '/mnt/containers/nextcloud:/data:rwm'
        #volume:
        #  - '/mnt/containers/nextcloud/config:/config'
        #  - '/mnt/containers/nextcloud:/data'
        ports:
          - '444:443'
        env:
          PUID: 1000
          PGID: 1000
          TZ: 'America/Los_Angeles'