#------ <https://github.com/NginxProxyManager/nginx-proxy-manager> ------ 
- name: Run Nginx Proxy Manager container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull Nginx Proxy Manager image
      containers.podman.podman_image:
        name: 'jc21/nginx-proxy-manager:latest'
        tag: latest

    - name: Create directories for Nginx Proxy Manager container
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '/mnt/containers/nginx-proxy-manager'
        - '/mnt/containers/nginx-proxy-manager/data'
        - '/mnt/containers/nginx-proxy-manager/letsencrypt'

    - name: Create Nginx Proxy Manager container
      containers.podman.podman_container:
        name: nginx-proxy-manager
        image: 'jc21/nginx-proxy-manager:latest'
        state: present
        restart_policy: unless-stopped
        # Only works with volume mounted on the host with the following command options (https://access.redhat.com/solutions/6415411)
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context="system_u:object_r:container_file_t:s0" /mnt/containerstorage
        # Why do I need to do both device and volume?        
        privileged: true
        device:
          - '/mnt/containers/nginx-proxy-manager/data:/data:rwm'
          - '/mnt/containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt:rwm'
        volume:
          - '/mnt/containers/nginx-proxy-manager/data:/data'
          - '/mnt/containers/nginx-proxy-manager/letsencrypt:/etc/letsencrypt'
        ports:
          - '443:443'
          - '80:80'
          - '81:81'