---
#------ Radarr <https://github.com/linuxserver/docker-radarr> ------
# https://wiki.servarr.com/radarr
- name: Run radarr container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull radarr image
      containers.podman.podman_image:
        name: 'lscr.io/linuxserver/radarr'
        tag: latest

    - name: Create directories for radarr container
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '/mnt/containers/radarr'
        - '/mnt/containers/radarr/config'
        - '/mnt/media/movies'
        - '/mnt/media/downloads/complete'

    - name: Create radarr container
      containers.podman.podman_container:
        name: radarr
        image: 'lscr.io/linuxserver/radarr:latest'
        state: started
        restart_policy: unless-stopped
        privileged: true
        # Storage works after running the following, why?
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context='system_u:object_r:container_file_t:s0' /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        device:
          - '/mnt/containers/radarr/config:/config:rwm'
          - '/mnt/media/movies:/movies:rwm'
          - '/mnt/media/downloads/complete:/downloads:rwm'
        network: 'container:protonvpn'
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/Los_Angeles
