#------ Readarr <https://github.com/linuxserver/docker-readarr> ------ 
# https://wiki.servarr.com/readarr
- name: Run readarr container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull readarr image
      containers.podman.podman_image:
        name: 'lscr.io/linuxserver/readarr'
        tag: develop

    - name: Create directories for readarr container
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '/mnt/containers/readarr'
        - '/mnt/containers/readarr/config'
        - '/mnt/media/books'
        - '/mnt/media/downloads/complete'

    - name: Create readarr container
      containers.podman.podman_container:
        name: readarr
        image: 'lscr.io/linuxserver/readarr:develop'
        state: started
        restart_policy: unless-stopped
        privileged: true
        # Storage works after running the following, why?
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context='system_u:object_r:container_file_t:s0' /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        device:
          - '/mnt/containers/readarr/config:/config:rwm'
          - '/mnt/media/books:/books:rwm'
          - '/mnt/media/downloads/complete:/downloads:rwm'
        network: 'container:protonvpn'
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/Los_Angeles