#------ transmission <https://github.com/linuxserver/docker-transmission> ------ 
- name: Run transmission container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull transmission image.
      containers.podman.podman_image:
        name: 'lscr.io/linuxserver/transmission:latest'
        tag: transmission

    - name: Create directories for transmission container
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - /mnt/media/downloads
        - /mnt/containers/transmission
        - /mnt/containers/transmission/downloads
        - /mnt/containers/transmission/config
        - /mnt/containers/transmission/watch

    - name: Create transmission container.
      containers.podman.podman_container:
        name: transmission
        image: transmission
        state: started
        restart_policy: 'unless-stopped'
        privileged: true
        # Only works with volume mounted on the host with the following command options (https://access.redhat.com/solutions/6415411)
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context="system_u:object_r:container_file_t:s0" /mnt/containerstorage
        # Why do I need to do both device and volume?
        device:
          - '/mnt/media/downloads:/downloads:rwm'
          - '/mnt/containers/transmission/config:/config:rwm'
          - '/mnt/containers/transmission/watch:/watch:rwm'
        volume:
          - '/mnt/media/downloads:/downloads'
          - '/mnt/containers/transmission/config:/config'
          - '/mnt/containers/transmission/watch:/watch'
        network: 'container:protonvpn'
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/Los_Angeles
          USER: "{{ TRANSMISSION_USERNAME }}"
          PASS: "{{ TRANSMISSION_PASSWORD }}"