#------ transmission <https://github.com/linuxserver/docker-transmission> ------ 
- name: Run transmission container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull transmission image.
      containers.podman.podman_image:
        name: 'lscr.io/linuxserver/transmission:latest'
        tag: latest

    - name: Create directories for transmission container
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - /mnt/media/downloads
        - /mnt/containers/transmission
        - /mnt/containers/transmission/downloads
        - /mnt/containers/transmission/config
        - /mnt/containers/transmission/watch

    - name: Create transmission container
      containers.podman.podman_container:
        name: transmission
        image: 'lscr.io/linuxserver/transmission:latest'
        state: started
        restart_policy: 'unless-stopped'
        privileged: true
        # Storage works after running the following, why?
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context='system_u:object_r:container_file_t:s0' /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        device:
          - '/mnt/media/downloads:/downloads:rwm'
          - '/mnt/containers/transmission/config:/config:rwm'
          - '/mnt/containers/transmission/watch:/watch:rwm'
        network: 'container:protonvpn'
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/Los_Angeles
          USER: '{{ TRANSMISSION_USERNAME }}'
          PASS: '{{ TRANSMISSION_PASSWORD }}'