---
#------ Prowlarr <https://github.com/linuxserver/docker-prowlarr> ------
# https://wiki.servarr.com/en/prowlarr
- name: Run prowlarr container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull prowlarr image
      containers.podman.podman_image:
        name: "lscr.io/linuxserver/prowlarr"
        tag: develop

    - name: Create directories for prowlarr container
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ CONTAINERS_PATH }}/prowlarr"
        - "{{ CONTAINERS_PATH }}/prowlarr/config"

    - name: Create prowlarr container
      containers.podman.podman_container:
        name: prowlarr
        image: "lscr.io/linuxserver/prowlarr:develop"
        # Next two are managed by systemd
        state: created
        restart_policy: "no"
        privileged: true
        # Storage works after running the following, why?
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context="system_u:object_r:container_file_t:s0",nolock /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        device:
          - "{{ CONTAINERS_PATH }}/prowlarr/config:/config:rwm"
        network: "container:protonvpn"
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/Los_Angeles
        generate_systemd:
          path: "/etc/systemd/system/"
          new: "yes"
          restart_policy: "on-failure"

    - name: Start prowlarr container
      ansible.builtin.systemd :
        name: "container-prowlarr.service"
        enabled: true
        state: started