---
#------ Sonarr <https://github.com/linuxserver/docker-sonarr> ------
# https://wiki.servarr.com/sonarr
- name: Run sonarr container
  hosts: rhel01
  become: true
  tasks:
    - name: Pull sonarr image
      containers.podman.podman_image:
        name: "lscr.io/linuxserver/sonarr"
        tag: latest

    - name: Create directories for sonarr container
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ CONTAINERS_PATH }}/sonarr"
        - "{{ CONTAINERS_PATH }}/sonarr/config"
        - "{{ MEDIA_PATH }}/tvshows"
        - "{{ MEDIA_PATH }}/downloads/complete"

    - name: Create sonarr container
      containers.podman.podman_container:
        name: sonarr
        image: "lscr.io/linuxserver/sonarr:latest"
        # Next two are managed by systemd
        state: created
        restart_policy: "no"
        privileged: true
        # Storage works after running the following, why?
        # mount -t nfs my-nfs-share.example.com:/opt/container-nfs-storage -o rw,context="system_u:object_r:container_file_t:s0",nolock /mnt/containerstorage
        # sudo setsebool -P container_use_devices=true
        device:
          - "{{ CONTAINERS_PATH }}/sonarr/config:/config:rwm"
          - "{{ MEDIA_PATH }}/tvshows:/tv:rwm"
          - "{{ MEDIA_PATH }}/downloads/complete:/downloads:rwm"
        network: "container:protonvpn"
        env:
          PUID: 1000
          PGID: 1000
          TZ: America/Los_Angeles
        generate_systemd:
          path: "/etc/systemd/system/"
          new: "yes"
          restart_policy: "on-failure"

    - name: Start sonarr container
      ansible.builtin.systemd :
        name: "container-sonarr.service"
        enabled: true
        state: started